<?php
$this->headTitle('Edit');

    if (isset($_POST['Edit']) && !empty($_POST['text']))
    {
        //$pdo = ?
        //  $parameters = array(':Description'=>$Description );
        //  $sth = $pdo->prepare('UPDATE edit SET Description=:Description');
        //  $sth->execute($parameters);

        //  $parameters2 = array('');
        //  $sth2 = $pdo->prepare('select * from edit');

        //  sth2->execute($parameters2);
        //  $row = $sth2->fetch();

        //  echo 'The text has been modified in the database and is now this: <br><br>';
        //  echo '<b>' .  echo $row['Description'] . '</b>';

        //    echo "The text has been added to the database: <br> <i>" . $text . "</i>";

    }

    else
    {
        echo "Wat het nu is: <br> <i>" . " </i> ";
        echo '<br /><br />';
        echo $this->form($form);

    }
//}
