<?php
$this->headTitle('Edit');

//$pdo = ?

if(isset($_POST['Edit']))
{
    $Description = $_POST['text'];

    //  $parameters = array(':Description'=>$Description );
    //  $sth = $pdo->prepare('UPDATE edit SET Description=:Description');
    //  $sth->execute($parameters);

    //  $parameters = array('');
    //  $sth2 = $pdo->prepare('select * from edit');

    //  sth2->execute($parameters);
    //  $row = $sth2->fetch();
    // ;

    //  echo 'The text has been modified in the database and is now this: <br><br>';
    //  echo '<b>' .  echo $row['Description'] . '</b>';

}

else
{
    $form = $this->form;
    echo $this->form($form);
}